### ISSUE TITLE
Livereload is trigger prematurely

### ISSUE THREAD

**Issue by jbarlow83** [wilr/grunt-shopify#42]
When grunt-shopify is set up as a watched task with livereload enabled it will do the following:
- detect changed file
- begin uploading changed file
- live reload the browser
- finish uploading file

It appears that it is sending some sort of premature completion signal back to grunt-contrib-watch instead of signalling completion when the file is actually done uploading.

Here's the relevant part of Gruntfile.coffee.

```
shopify:
  options:
    base: "deploy/"
watch:
  configFiles:
    files: ["Gruntfile.coffee"]
    options:
      reload: true
  shopify:
    files: ["deploy/**"]
    tasks: ["shopify"]
    options:
      livereload: true
```
##
